[pyprland]

plugins = [
  "scratchpads",
  "magnify",
  "workspaces_follow_focus",
  "monitors",
  "expose",
]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "60% 55%"
